name: magic_box_app
description: 魔盒APP，物品收纳管理工具
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  super_drag_and_drop: ^0.8.24
  photo_view: ^0.14.0
  speech_to_text: ^7.0.0
  flutter_swiper_view: ^1.1.6
  stacked_card_carousel: ^0.0.4
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  file_picker: ^10.1.9
  sqflite_common_ffi: ^2.3.0
  webview_flutter: ^4.4.2
  uuid: ^4.2.1
  fl_chart: ^0.65.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  crypto: ^3.0.3
  path: ^1.8.3
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

assets:
  - assets/sounds/pop.mp3
  - assets/images/
  - assets/web/three_box.html
  - .env
